version: 1.2
workflows:
   - name: perturbSeq
     subclass: WDL
     primaryDescriptorPath: /perturbSeq-analysis.wdl
     testParameterFiles:
     -  /perturbSeq-analysis.tutorial.inputs.json
     readMePath: /README.md
     authors:
       - name: Yueyao Gao
         email: gaoyueya@broadinstitute.org
         role: Developer
         affiliation: Broad Institute
         orcid: 0000-0002-7607-2938